const emoji = {
  a: "smile",
  b: "disappointed",
  c: "worried",
  d: "angry",
  e: "rage",
  f: "cry",
  g: "grinning",
  h: "persevere",
  i: "triumph",
  j: "disappointed_relieved",
  k: "frowning",
  l: "anguished",
  m: "sunglasses",
  n: "kissing_heart",
  o: "sleepy",
  p: "tired_face",
  q: "yum",
  r: "kissing_smiling_eyes",
  s: "heart_eyes",
  t: "kissing_closed_eyes",
  u: "stuck_out_tongue",
  v: "stuck_out_tongue_winking_eye",
  w: "stuck_out_tongue_closed_eyes",
  x: "sweat_smile",
  y: "joy",
  z: "grin",
};

module.exports = emoji;
